### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by wachira-cipher**
this is my pull-REQUEST

### CODE REVIEW

**Comment by Cyrus-Muchiri** [comment]
Kindly add a screen shot of what the page looks like

**Comment by Cyrus-Muchiri** [comment]
Where is the sql file.
I cannot see where you add the data to the database

**Comment by wachira-cipher** [comment]
image

**Comment by wachira-cipher** [comment]
i am creating another branch and pull request with the corrections

**Comment by Cyrus-Muchiri** [comment]
No, you dont do that.
You use the same branch so that we can follow with one conversation.

Basically, 1 PR for every task

**Comment by Cyrus-Muchiri** [comment]
Kindly reopen this and push here

**Pull request closed without merging**
